### ISSUE TITLE
[Feature Request v3] Add ability to hide content app on specific doc types

### ISSUE THREAD

**Issue by TQ-Benji** [skybrud/Skybrud.Umbraco.Redirects#120]
I have a case that for some nodes the redirect content app is not needed. These nodes also have no properties so no content tab which causes on creation of the node the name field to be disabled in the redirects tab. Editors are then thrown off as they "can't" save the node as you have to change tab to Info first in order to continue creating the node.

![image](https://user-images.githubusercontent.com/60918405/148048950-ba529036-30cc-4177-869e-66a8e2faca11.png)

Would it be possible to add some config to be able to disable the redirect tab on nodes or doc types that are not needed? something that is similar to the hide/show outlined in https://our.umbraco.com/documentation/extending/Content-Apps/ as you are creating the content app via code I couldn't set this via the package.manifest

If i'm missing a solution to how to do this already please let me know

thanks

**Comment by abjerner** [comment]
Hi @EM-Benji 

I've been debating a bit with myself whether the content app should be enabled by default. There currently is a check so the content app is only shown for content types, but not for element types. Checking whether the content item has a template or something similar could perhaps be another relevant check.

Anyways - the content app is registered through C#, which is why you can't find it in the `package.manifest` file. The redirects package features a class called `RedirectsBackOfficeHelper`, which (among other things) controls the content app. The class is hooked up with dependency injection, meaning you can replace it with your own class inheriting from `RedirectsBackOfficeHelper` - eg. as shown here:

```csharp
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Skybrud.Umbraco.Redirects.Composers;
using Skybrud.Umbraco.Redirects.Helpers;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Models.ContentEditing;
using Umbraco.Cms.Core.Models.Membership;
using Umbraco.Cms.Core.Services;
using Umbraco.Extensions;

namespace web.Redirects {
    
    [ComposeAfter(typeof(RedirectsComposer))]
    public class MyRedirectsComposer : IComposer {

        public void Compose(IUmbracoBuilder builder) {
            builder.Services.AddUnique<RedirectsBackOfficeHelper, MyRedirectsBackOfficeHelper>();
        }

    }

    public class MyRedirectsBackOfficeHelper : RedirectsBackOfficeHelper {
        
        public MyRedirectsBackOfficeHelper(IRuntimeState runtimeState, IHttpContextAccessor httpContextAccessor, LinkGenerator linkGenerator, IDomainService domainService, IContentService contentService, IMediaService mediaService, ILocalizedTextService textService) : base(runtimeState, httpContextAccessor, linkGenerator, domainService, contentService, mediaService, textService) {

        }

        public override ContentApp GetContentAppFor(object source, IEnumerable<IReadOnlyUserGroup> userGroups)  {

            switch (source) {

                case IContent content:

                    // Disable the content app for pages that don't already have a template
                    if (content.TemplateId == null) return null;
                    
                    // Disable the content app for pages that can't have a template
                    if (content.ContentType.DefaultTemplate == null) return null;

                    // Disable the content app for a specific content type
                    if (content.ContentType.Alias == "thatContentTypeWithNoProperties") return null;

                    // Default behavior
                    return content.ContentType.IsElement ? null : GetDefaultContentApp();

                case IMedia media:
                    return media.ContentType.Alias == Constants.Conventions.MediaTypes.Folder ? null : GetDefaultContentApp();

                default:
                    return null;
                
            }

        }

    }

}
```

The example illustrates a few different checks that can be used to disable the content app:

- If a content item doesn't have a template, `content.TemplateId` will be `null`. Downside is that when creating a new content item, it won't have a template initially - and even when saving the content item, the content app won't appear until you reload the page or view another content item, and then goes back to the one you just created.

- If no templates are allowed, `content.ContentType.DefaultTemplate` is `null`, which might perhaps then be your best option. Technically content items could still have a template if they were saved before any templates were disallowed.

- `content.ContentType.Alias` (or similar properties) lets you check against specific content types

Calling `content.ContentType` exposes the content type as an instance of `ISimpleContentType`, which is rather limited in terms of information. For instance, we can check whether the content type has any properties. if you need this, you could inject `IContentTypeService`, and then look up the full `IContentType` - but that might have a slight cost in performance.

Hope that helps you out ;)
