### ISSUE TITLE
Support changing Backoffice UmbracoPath

### ISSUE THREAD

**Issue by iFaxity** [skybrud/Skybrud.Umbraco.Redirects#140]
As per Security Hardening in Umbraco 9, changing the Backoffice base url is recommended (https://our.umbraco.com/documentation/reference/security/Security-hardening/#rename-your-umbraco-folder).

However in this plugin the URL to the plugins backend is hard-coded in the class **RedirectsBackOfficeHelper**. Reference: https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/af88c0cfb15d76147c0555dc2d3bf681a874c5c7/src/Skybrud.Umbraco.Redirects/Helpers/RedirectsBackOfficeHelper.cs#L96-L106

Which means that the plugin in Backoffice doesn't work at all, as it gets 404's when trying to access the API's. Not sure how we can get the root URL except for getting the value direcly from Appsettings (Key: Umbraco.CMS.Global.UmbracoPath). Maybe checking ServerVeriables for the umbracoBaseUrl?

**Comment by abjerner** [comment]
Hi @iFaxity - thanks for reporting this 👍 

This is an oversight - possibly because I didn't now how to look up the Umbraco path at the time, and thought I'd fix it later.

Even though the URL is hardcoded in C#, it should already be dynamic in Angular components, so I'd imagine the following will work:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/ce4aff37777727d10a23571ecd6cb1b6e4860309/src/Skybrud.Umbraco.Redirects/Helpers/RedirectsBackOfficeHelper.cs#L99-L103

I still need to test it though. I will try to find some time for doing that and pushing a new release 😉

**Comment by iFaxity** [comment]
Great! Thanks for the quick response.

**Comment by abjerner** [comment]
Hi @iFaxity 

I found a few more places I need to fix, which was released as part of [**v3.0.4**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v3.0.4) the other day.

I've also started to release alpha versions for Umbraco 10, where I've made the same changes. This is now part of the [**v4.0.0-alpha002**](https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.0-alpha002) release. It seems that Umbraco it self doesn't fully support changing the backoffice URL due the way they are handling static assets, but for V10 this will depend on what Umbraco does.
