### ISSUE TITLE
Make it possible to disable the content app

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.Redirects#141]
I really don't like that the package now adds a content app to ALL nodes displaying redirects for that specific node. Can we have a config option to disable this, or maybe disable/enable based on content type alias?

**Comment by abjerner** [comment]
Hi @skttl 

When adding the content app I wasn't sure whether it should be enabled or disabled by default, but it ended up being enabled by default since it seemed that would fit most use cases.

There is no config option to disable the content app (at least not yet), but the content app is instead controlled by the `RedirectsBackOfficeHelper` class. You can replace it with your own implementation and override the `GetContentAppFor` method like described here:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/120#issuecomment-1006653911

And yes, this should be documented 😊

**Comment by abjerner** [comment]
Now there's a bit of documentation here:

https://packages.skybrud.dk/skybrud.umbraco.redirects/docs/v3/configuration/content-app/

**Comment by abjerner** [comment]
Hi @skttl 

I haven't heard back from you, so just wanted to check whether this was a viable solution for you?

I think the backoffice helper gives you the most amount of control. But I guess a config section in `appsettings.json` could also make sense when you only need something simple 🤔

**Comment by skttl** [comment]
Good enough for me, thanks! 👍
