### ISSUE TITLE
Keep design consistent with Umbraco backoffice

### ISSUE THREAD

**Issue by mastrup** [skybrud/Skybrud.Umbraco.Redirects#15]
The user experience could be streamlined if the listview matched the Umbraco Redirect URL Management.
I was thinking of:
- moving the redirect icon
- renaming the "destination" column to "redirected to"
- Color the "delete" button and rename it to "remove"

![Updated view](http://i.imgur.com/cQxXdXN.png)

And this is how the Umbraco Redirect URL Management looks:
![Umbraco redirect url management](http://i.imgur.com/OO41lep.png)

Could this be an idea?

**Comment by abjerner** [comment]
Thanks again :D

The redirects list view was more inspired by the regular Umbraco list views - but you have some good points. I'll look into fixing that ;)

**Comment by bjarnef** [comment]
Also note the style issue with the buttons "Add new redirect" and "Reload".

It happens because the Diplo Trace Log Viewer unfortunately force `select` tags to 100% width.
![image](https://cloud.githubusercontent.com/assets/2919859/26619026/f19f24b2-45dc-11e7-8b8f-e37a8c9d62dd.png)

![image](https://cloud.githubusercontent.com/assets/2919859/26619051/055a531e-45dd-11e7-9ced-a95d478466ab.png)

It seems Umbraco Cloud projects haven't been updated with latest version of the package, which has fixed the issue:
https://github.com/DanDiplo/UmbracoTraceLogViewer/issues/23

**Comment by abjerner** [comment]
Thanks to the pull request from @skttl and a few changes of my own, the table now looks like this:

![image](https://user-images.githubusercontent.com/3634580/30456756-2ce022d0-99a5-11e7-9e53-f0fbe656e9ed.png)

I haven't yet looked into the issue with Diplo Trace Log Viewer, but I'll try to look into that as well for the next release ;)

**Comment by abjerner** [comment]
@mastrup @bjarnef Is the styling from Diplo Trace Log Viewer still an issue with this package? What version is Umbraco Cloud using now?

**Comment by bjarnef** [comment]
@abjerner no I don't think it is an issue anymore, when updating the Diplo Trace Log Viewer package. I was using Umbraco 7.5.14 on Umbraco Cloud, but I realized after talking with the Umbraco support team that only new projects got latest version of Diplo Trace Log Viewer, so existing project didn't get the package updated. But I could update the package by myself via NuGet.

**Comment by abjerner** [comment]
@bjarnef thanks for the info 👍
