### ISSUE TITLE
Feature request: Forward querystring

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#17]
It would be nice if this redirect package supported forwarding querystring like UrlTracker does.

![image](https://user-images.githubusercontent.com/2919859/27530089-5e003e6e-5a57-11e7-8d7c-d846bebe87bc.png)

**Comment by martijn1k** [comment]
+1

This would be extremely useful... Adwords/Tag Manager/Analytics etc. are adding all kind of querystring decorations. We've just relaunched a site and noticed that querystrings are ignored in forwards, as well as static file extensions (I noticed another issue for this).

By the way guys... I LOVE this package, great work. 
Much much nicer than the 301 Tracker.

Keep up the good work!

**Comment by abjerner** [comment]
Thanks for the feedback. The package has been a bit neglected over the summer due to vacation etc., but I've just pushed a new release to fix some of the low hanging fruits. I will try to look into this issue as well ;)

**Comment by martijn1k** [comment]
Excellent news! Yeah understandable man, taking a well deserved break is important too right?

I think there are some pull requests relevant to both issues.

Your package could easily be the long awaited replacement for the 301 tracker from Mr Kips who no longer maintains it, since that package no longer works for new Umbraco installs (7.6+).

It's much faster, looks great, integrates well. 

So basically... Shut up and take my money ;)

Good luck with the further development, I'll be following this package closely.

Let me know if you need help testing. I have several environments running in production.

**Comment by abjerner** [comment]
The pull request has now been merged, and will be part of the next release (which will probably be released over the weekend once I have done some more testing).
