### ISSUE TITLE
Redirects not firing

### ISSUE THREAD

**Issue by steadygo-jo** [skybrud/Skybrud.Umbraco.Redirects#170]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.8

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 11.2.1

### Bug description

The package reference is in place for 4.0.8 and the CMS dashboard is fully functional.

I create a redirect e.g. /xyz to go to a published page e.g. /news

I go to url /xyz and the page shown is that which is defined as the 404 Not Found page.

In network trace no 301 is fired - all shows as 200 - which I assume is because umbraco is not creating a 301 for for Page Not Found

**Comment by BarryFogarty** [comment]
I just came on to see if this was reported, I am experiencing the same (Umbraco v11.2.2).  Nothing notable in the log.

**Comment by steadygo-jo** [comment]
I have also added verbose logging and the mini profiler to my local instance and see no attempt to read anything from a table other than the Umbraco redirects table itself.

**Comment by abjerner** [comment]
Hi both

If your 404 page returns 200, then your 404 page is not working correctly, and it's not an issue with this package. There is a bit more information here:

- [Why doesn't my redirects work?](https://packages.skybrud.dk/skybrud.umbraco.redirects/docs/v4/faq/#why-doesnt-my-redirects-work)

If you set up your 404 page via Umbraco's `Error404Collection` setting, there is a bug in 11.2 which means the status code is 200 instead of 404. You can read more about this here:

- [404 error page configured via `Error404Collection` doesn't return 404 in 11.2](https://github.com/umbraco/Umbraco-CMS/issues/13907)

This was fixed in Umbraco 11.3, so upgrading to this version should fix the issue.

**Comment by steadygo-jo** [comment]
I will try now ...

Results are in ... resolved!
