### ISSUE TITLE
Redirects with file extensions

### ISSUE THREAD

**Issue by dmiller21283** [skybrud/Skybrud.Umbraco.Redirects#172]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.8

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3

### Question

We have some redirects defined to handle pages from our old site. Some of these have a .jsp extension. These redirects used to be handled properly but now just return 200 with an empty response. Is this a configuration that needs to be handled within the package, Umbraco, or ASPNET Core?

Any insight is much appreciated.

**Comment by abjerner** [comment]
Hi @dmiller21283 

If the URLs return `200 OK`, it's because you have some other logic (eg. a custom middleware or similar) that changes the response. A default Umbraco installation seems to return `404 Not Found` for .jsp URLs:

![image](https://user-images.githubusercontent.com/3634580/235469426-2f330b93-4ab9-4d88-871e-01a891cb3df0.png)

When testing out in 11.3.1, I have no problems creating redirects for .jsp URLs.

As this appears to be a local issue, I'm afraid it's not something I can help with. You can try asking your question on [Our Umbraco](https://our.umbraco.com/) or Umbraco's Discord channel and hope it rings a bell for someone 😉 

Also, again please be specific with the Umbraco version. It probably doesn't matter much for this particular issue, but 11.3 could mean both 11.3.0 and 11.3.1.
