### ISSUE TITLE
Umbraco 12 compatibility

### ISSUE THREAD

**Issue by skttl** [skybrud/Skybrud.Umbraco.Redirects#176]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.12

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0

### Question

The upper limit on the nuget package prevents it from being installed with Umbraco 12 - I just tried doing a local version of the package though, and it works as expected in 12.

So maybe a new release without the upper dependency?

**Comment by abjerner** [comment]
Hadn't realized Umbraco 12 was out today 😆 

But yes - I haven't encountered any issues when testing the package on the release candidates, so I'll look into changing the upper bound 😉

**Comment by abjerner** [comment]
And a new release is out: https://github.com/skybrud/Skybrud.Umbraco.Redirects/releases/tag/v4.0.13

I did spot a minor issue with timestamps being shown with incorrect offset. Not sure whether that is due to Umbraco 12 or because I were testing with SQLite instead of SQL server: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/177
