### ISSUE TITLE
Doesnt work with Hebrew 

### ISSUE THREAD

**Issue by avialonn** [skybrud/Skybrud.Umbraco.Redirects#180]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.13

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10

### Bug description

Hi all,
Redirect is not working for Hebrew. 
Any input will be appreciate.
aa

**Comment by abjerner** [comment]
Hi @avialonn 

Please provide some more information about what you think the issue is. I haven't really tested specifically with Hebrew characters before, but when doing some quick tests, it seems to work fine.

There isn't a Hebrew translation available for this package. It's not something we will work on, but I'd be happy to accept any PR that adds this 😉

**Comment by avialonn** [comment]
Many thanks for your quick response.
I mean that the redirect does not take place and instead we are being redirected to homepage. 
English urls works as expected.
