### ISSUE TITLE
Configured redirects not working

### ISSUE THREAD

**Issue by brianmac1967** [skybrud/Skybrud.Umbraco.Redirects#185]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

2.1.4

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.17.1

### Bug description

I have added in 2 redirects after installing Skybrud Redirects but the redirect is not occuring even though the source and destination URLs are valid.

I expect the redirect to occur everytime each page is visited not just when exceptions occur.

See screenshot below:

<img width="744" alt="image" src="https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/116564873/994494af-56f3-4c43-8567-b61777c6ad19">

My config is set up as below:

<img width="863" alt="image" src="https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/116564873/ec3f254c-d6ba-47bf-9380-31addf363eaf">

Thank you

**Comment by abjerner** [comment]
Hi @brianmac1967 

What does happen when you try to visit one of these redirects?

The redirect module only kicks in if the server responds with a 404 status code. Typically if redirect do not work, it's because the server responds with a 200 OK status code.

I can't see from your screenshot, but a possible reason could also be that another page exists at the original URL. if that is the case, the user will see the page instead of being redirected.
