### ISSUE TITLE
Redirection not working, missing information in documentation?

### ISSUE THREAD

**Issue by Dabendorf** [skybrud/Skybrud.Umbraco.Redirects#188]
### Which version of Skybrud Redirects are you using? (Please write the *exact* version, example: 4.0.8)

4.0.17

### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Question

Hi,
I installed everything in Umbraco and also see redirection functionality in the backoffice, but nothing actually happens. I checked with the FAQ and my pages all properly say ERROR 404 as it should be.

I am starting to ask myself it I should have done more than just installing everything? Does one need to put in code somewhere as well?
The documentation says that one can add custom helpers (https://packages.skybrud.dk/skybrud.umbraco.redirects/docs/v4/configuration/) but do I also need to generate one if I dont want it to be customised?

![image](https://github.com/skybrud/Skybrud.Umbraco.Redirects/assets/9696353/e8486581-5074-415a-bd2b-b5718bfe36d3)

**Comment by abjerner** [comment]
Hi @Dabendorf 

Based on the information that you've provided, I'd say it should work. Adding a custom helper is only necessary to customize parts of the package through C#.

Since it still doesn't work, can you share a bit more about your setup? Have you configured some custom 404 error handling? Can you share your `Startup.cs` and `Program.cs`? Remember to blank out if you have any sensitive information 😉

**Comment by Dabendorf** [comment]
Hi, Thanks for your message. I actually found out what the problem was. The problem is if you have several websites in Umbraco but not everything has its own domain, but all of them have like /fi/, /no/ etc and you choose one specific, one needs to keep writing the website path like /fi/, /no/ as well. We thought that this wasn't necessary. It seems like everything works fine. Thank you for the great package and your quick answer.
