### ISSUE TITLE
Umbraco package

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#30]
I noticed that this project only exists as a NuGet package: https://github.com/skybrud/Skybrud.Umbraco.Redirects/tree/master/releases

Any reason for not having a Umbraco package and a project on our.umbraco.org?
I might be easier for people to find or know about the package and since many of the other Skybrud-packages exists on Our.

**Comment by abjerner** [comment]
This is probably due to a combination of a few things. Each way we release our packages is also another way we need to test each new release, which requires some extra time. I have messed up the Umbraco releases for some of our other packages as I've forgotten to test them. Also, this package started as an internal project, so I haven't really gotten around to release it as an Umbraco package.

**Comment by abjerner** [comment]
Hi @bjarnef,

This took a bit longer than it should have, but the package is now also available as an Umbraco package:

https://our.umbraco.com/packages/website-utilities/skybrud-redirects/
