### ISSUE TITLE
Change button style of "Add new redirect"

### ISSUE THREAD

**Issue by bjarnef** [skybrud/Skybrud.Umbraco.Redirects#40]
Maybe it would be better to change style of the button "Add new redirect"?

![image](https://user-images.githubusercontent.com/2919859/47090817-eefc4a80-d223-11e8-87be-5606b93c15fa.png)

It could be something like this using the class `btn-info`.

![image](https://user-images.githubusercontent.com/2919859/47091204-ad1fd400-d224-11e8-82b3-897a8e72ba3e.png)

**Comment by abjerner** [comment]
@bjarnef Wouldn't `btn-primary` or `btn-success` be more suitable? They are styled the same way, and gives a green button instead of purple. Umbraco seems to be using this as well (or at least in the users section):

![image](https://user-images.githubusercontent.com/3634580/47099761-486d7500-d236-11e8-83e5-fa498b978d9c.png)

Anyways - how did you get a white text color for the button in your screenshot? If I only add the `btn-info` class, the text is still black. I guess you did something more?

**Comment by bjarnef** [comment]
Yes, I think it could use `btn-primary` or `btn-success` instead. I think Umbraco doesn't use this style much in dashboard because of the save button in the footer.

**Comment by abjerner** [comment]
Time flies. While I should have look at this at the time, I'm closing this issue as it relates to the Umbraco 7 version of this package.
