### ISSUE TITLE
How to create a redirect to an external page?

### ISSUE THREAD

**Issue by lcichanowicz** [skybrud/Skybrud.Umbraco.Redirects#55]
Hi.  How do I create a redirect from a non-existent URL in my site to an external URL (on another site)?

**Comment by abjerner** [comment]
Hi @lcichanowicz,

You haven't specified what version of Umbraco you're using, so here are some screenshots from the Umbraco 8 package (Umbraco 7 is roughly the same):

**Click on the *Add new redirect* button, and then on *Select destination* in the overlay:**

![image](https://user-images.githubusercontent.com/3634580/64888201-a1be6e00-d66a-11e9-8147-4533ef82063d.png)

**Instead of selecting a content item within Umbraco via the tree in the bottom of the next overlay, you can specify a custom URL:**

![image](https://user-images.githubusercontent.com/3634580/64887997-278de980-d66a-11e9-8e7c-5293d7bb1282.png)

**Comment by lcichanowicz** [comment]
@abjerner, I apologize for that.  I am using Umbraco 7.14.  Thanks for the swift reply.

Since I cannot add a redirect on the "global" tab in Content, I was doing so on the Home node.  I just did not realize I had to 'Remove' the default Destination to get the full URL options.  Thanks!

![image](https://user-images.githubusercontent.com/4871064/64890859-83db1400-d63e-11e9-93bc-504f6589ceba.png)

![image](https://user-images.githubusercontent.com/4871064/64890930-a66d2d00-d63e-11e9-9228-9095b1d4e11a.png)

![image](https://user-images.githubusercontent.com/4871064/64890969-b84ed000-d63e-11e9-8acb-9eecb4e086f9.png)

**Comment by lcichanowicz** [comment]
@abjerner, I added my external redirect on my Home page, but where did it go?  It is not in the list; but, the redirect works.  It does not show on the "global" Content node either.

**Comment by abjerner** [comment]
I'm not sure what you mean by the global content node. If you have installed the dashboard, all redirects should be shown there:

![image](https://user-images.githubusercontent.com/3634580/64906926-84ca7f00-d6ec-11e9-8fec-deca9b749b0e.png)

**Comment by lcichanowicz** [comment]
@abjerner, I finally got around to adding the dashboard.  I was confused by the docs.  (I was inadvertently in the Umbraco 8 Skybrud.Umbraco.Redirects GitHub.)

They reference a non-existent image:

> Besides the dashboard shown in the top of this page

https://github.com/skybrud/Skybrud.Umbraco.Redirects#screenshots

That image exists in the Umbraco 7 Skybrud.Umbraco.Redirects GitHub.

https://cloud.githubusercontent.com/assets/3634580/22441437/ac65dc6e-e737-11e6-8a5c-e89a46aea3a1.png
