### ISSUE TITLE
Installing nuget breaks the project

### ISSUE THREAD

**Issue by FransdeJong** [skybrud/Skybrud.Umbraco.Redirects#58]
When installing the nuget package I get the following error:
Umbraco version is 8.2.0
Redirect version is 2.0 (latest version on nuget)

```
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

[InvalidOperationException: Unable to resolve type: Skybrud.Umbraco.Redirects.Routing.RedirectsInjectedModule, service name: ]    LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) +382    LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) +78    LightInject.ServiceContainer.GetInstance(Type serviceType) +152    Umbraco.Core.Composing.LightInject.LightInjectContainer.GetInstance(Type type) +10    Umbraco.Core.FactoryExtensions.GetInstance(IFactory factory) +56    Umbraco.Web.Composing.ModuleInjector`1.Init(HttpApplication context) +163    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +523    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303  [HttpException (0x80004005): Unable to resolve type: Skybrud.Umbraco.Redirects.Routing.RedirectsInjectedModule, service name: ]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +659    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +189

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4001.0
```

If I refer to the RedirectsInjectedModule in code it is there. So something with the order of loading dependancies?

**Comment by abjerner** [comment]
Hi @FransdeJong,

Is this an upgraded project or a fresh install? Does it work if you create a new project, install Umbraco 8.2.0 and then the stable release of the redirects package? I tried doing that yesterday, and everything was working fine.

It does however sound like much like the issue described here: https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/53

But that was fixed in one of the alphas, and it should only have occurred during Umbraco upgrades.

Anyways, just be sure, and check the product version of the `Skybrud.Umbraco.Redirects.dll` file in your bin folder?. It should look something like this:

![image](https://user-images.githubusercontent.com/3634580/66915820-3a555e80-f01a-11e9-8326-1f5dc82e6949.png)

**Comment by FransdeJong** [comment]
Ok... I don't understand it anymore...

What I did:
Upgrade Umbraco from 8.1.5 to 8.2
Work on multiple things and everything was fine.
Installed the redirects package and project breaks
Uninstall the package again and work on some views
Install the package again to check the properties of the Dll and the package works...

So... issue fixed?

**Comment by abjerner** [comment]
I'm still not entirely sure what could have caused this. I'll close for issue for now, but we can always come back to it later if you or other users report the same again.
