### ISSUE TITLE
Multilingual site

### ISSUE THREAD

**Issue by filefontaine** [skybrud/Skybrud.Umbraco.Redirects#63]
Hello,
I have a multilingual site (3 for the moment).

I can create redirection with my default / mandatory language but I didn't find a way to create a redirection for the 2 other.

Did I miss something?

_I try a lot of different way, say me if you want the list._

**Comment by abjerner** [comment]
Hi @filefontaine,

The answer is most probably that this is currently not supported. But in order to be able to give an answer beyond that, can you help me with some more details?

Which versions of Umbraco are we talking about? And which version of this package? Does multilingual refer to using variants, or some other form of multilingual setup?

**Comment by filefontaine** [comment]
Hello @abjerner ,

Yes sorry for not giving basic information.
Umbraco version is 8.5.3, I use the basic multilingual integration offered on Umbraco 8.

I have 3 languages, for each i have setup a hostname (like /en, /de).

**Comment by abjerner** [comment]
Hi again @filefontaine,

Is *basic multilingual integration* the same as what Umbraco calls *variants*? Either way, multilingual sites are currently not supported.

If you can elaborate a bit more on what you're trying to do, I can try having a look at it 😉

**Comment by ronaldbarendse** [comment]
Culture variants aren't correctly supported indeed, as it would require selecting content in a specific culture (there's an open Umbraco issue about this: https://github.com/umbraco/Umbraco-CMS/issues/7546).

Because this package always redirects to the URL stored in the database (still an open issue I commented about earlier https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/36), it's possible to manually change the `DestinationUrl` in the database.

If the original/incoming redirect URL does start with one of the configured domains (the root node has multiple domains like `/en` for English and `/nl` for Dutch), it's possible to determine the correct culture and update the destination URL.

![Culture and hostnames](https://user-images.githubusercontent.com/1051287/81700166-9a08d080-9468-11ea-8854-a950a9287db1.png)

If you add the following code into `App_Data\MaintenanceController.cs` and request `/umbraco/backoffice/api/maintenance/updateredirects` (after being logged in), all destination URLs will be updated to the correct culture variant/version:

```c#
using System.Linq;
using System.Web.Http;
using Skybrud.Umbraco.Redirects.Models;
using Umbraco.Web.WebApi;

public class MaintenanceController : UmbracoAuthorizedApiController
{
	private readonly IRedirectsService redirectsService;

	public MaintenanceController(IRedirectsService redirectsService)
	{
		this.redirectsService = redirectsService;
	}

	[HttpGet]
	public void UpdateRedirects()
	{
		var redirects = this.redirectsService.GetRedirects(1, int.MaxValue, "content");
		var domains = this.UmbracoContext.Domains.GetAll(true);

		foreach (var redirect in redirects.Items)
		{
			var culture = domains.FirstOrDefault(d => redirect.Url.StartsWith(d.Name))?.Culture.Name ?? this.UmbracoContext.Domains.DefaultCulture;
			redirect.LinkUrl = this.UmbracoContext.Url(redirect.LinkKey, culture);

			this.redirectsService.SaveRedirect(redirect);
		}
	}
}
```

**Comment by ronaldbarendse** [comment]
@abjerner This line is responsible for always using the saved URL:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/12cffb0d8a1673c32670bb277f61cf27694f72b1/src/Skybrud.Umbraco.Redirects/Routing/RedirectsInjectedModule.cs#L73

This should be updated to get the current URL for content and media (as it could be updated in the meantime). As the domain is also available, that could be used to also get the URL in the correct culture.

**Comment by abjerner** [comment]
@ronaldbarendse while this package _should_ support multilingual sites, my time is a bit parse a the moment. So this comment is mostly just to acknowledge that I've seen your comments 👍

**Comment by ronaldbarendse** [comment]
@filefontaine I've just noticed the link picker uses the content tree language, so if you're adding/editing the redirect, you must make sure this is set to the correct language.

As the culture isn't stored (only the resulting redirect URL), editing the redirect destination will use the current content tree language again, so make sure to change this to the correct language before editing!

@abjerner It already sort-of does and most functionality to correctly do so largely depends on Umbraco core features (if you're using the built-in link picker)...

**Comment by rly-nozebra** [comment]
Hi @abjerner 
Any plans on implementing support for multilingual sites (variants)? Or is it waiting for any core functionality?

**Comment by bjarnef** [comment]
Hi @abjerner
I am currently working on a multi-site solution where each site has a single root node (Home Page), but these vary by culture. Some of the site only use English, while others use both English and French.

I tried installing latest v2.0.7, but it seem only do show English version in redirects dashboard and content tree for English version in tree picker in redirect dialog.

**Comment by abjerner** [comment]
@bjarnef As far as I can tell, Umbraco's link picker editor/overlay, which this package is using, still doesn't support variants. Ideally once you have selected a node, there should be an option to select a variant.

I thought about creating my own overlay instead - both to address variants as well as other issues. But this adds more complexity, and also requires more time, which I haven't had.

**Comment by bjarnef** [comment]
@abjerner maybe the editor could select the variant/culture first and the redirect was stored as a specific culture or invariant culture using * similar to the core redirects?

**Comment by ronaldbarendse** [comment]
Issue https://github.com/umbraco/Umbraco-CMS/issues/7546, which I linked earlier, addresses the missing culture selection/dropdown in the link picker, but is blocked by how to return/store this culture (e.g. change the return type or include the culture within the UDI). I think adding the culture within the UDI is the best solution (so you'd get `umb://document/[GUID]?culture=en`), but that would require changes within the CMS first, before support can be added to this package.

Currently, there's both a workaround for updating existing redirects (see my [example code above](https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/63#issuecomment-627363033)) and having the correct culture selected when adding new redirects ([change the tree language before opening the link picker](https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/63#issuecomment-630013853)).

As also [mentioned earlier](https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/63#issuecomment-627409023), because the URL of the selected content is saved and used for the redirect, these workarounds currently use the correct (but possibly outdated) URL. If the redirect would actually use the saved UDI to get the URL, it would currently need to store the culture separately to ensure the correct culture variant URL is used for the redirect.

**Comment by abjerner** [comment]
@ronaldbarendse I remember seeing Marcin working on that. I think Umbraco's issue with how it's stored is bigger than in relation to this package. If this is build into the link picker overlay, it could ideally return the culture as a separate property. That would be sufficient for this package.

A simple solution (I think) could be to use the current link picker overlay as the package is doing today, but then look up the selected content node via an API, and if it varies by culture, then prompt the user to select the desired culture. And if it doesn't vary, then just continue like normal. But this of course needs some testing.

The redirects package isn't storing a UDI, but rather a GUID as well as the type (URL, content or media). I don't think adding a column for the culture would require much work, so this at least can be supported at the database level.

> As also mentioned earlier, because the URL of the selected content is saved and used for the redirect, these workarounds currently use the correct (but possibly outdated) URL. If the redirect would actually use the saved UDI to get the URL, it would currently need to store the culture separately to ensure the correct culture variant URL is used for the redirect.

URLs for content and media **should** be resolved at runtime when redirecting the user. The fact that it isn't is an oversight (I thought for sure it already worked that way).

**Comment by abjerner** [comment]
This package - both for Umbraco 8 and Umbraco 9 - still relies on Umbraco link picker overlay, which doesn't support picking a specific culture. So to solve the problem described in this issue, the link picker in Umbraco would have to be updated first - or I would have to write my own link picker, which is not a small task.

So while this is still relevant, I'm closing the issue, as it's not something I currently have the time for - but I've marked the issue as **should-have** so I can get back to at some point the future.
