### ISSUE TITLE
Migrate from prop editor to content app

### ISSUE THREAD

**Issue by TimGeyssens** [skybrud/Skybrud.Umbraco.Redirects#67]
Think it might make sense to move the prop editor to a content app in v8... since you aren't actually storing data against the node right?

**Comment by rpjengaard** [comment]
I think @TimGeyssens could be right @abjerner . Thought about this as well.

**Comment by abjerner** [comment]
Yes. There probably should be a content app 👍 

My reason for not doing it so far is because we usually also use the property editor for an outbound redirect, which does save data on the property. So when having both inbound and outbound redirects, it makes sense to have them together.

![image](https://user-images.githubusercontent.com/3634580/76847307-266c8d80-6842-11ea-8014-4bcc35685fc4.png)

**Comment by TimGeyssens** [comment]
@abjerner ah ok makes sense then, though it was only a list of items... with no data stored in the umbraco db

**Comment by abjerner** [comment]
@TimGeyssens that is correct for the inbound redirects. They are stored in it's own database table. So it should be a content app ;)

Ideally the content app would be added by default, and then we can remove the content app and use the property editor instead in our case.

**Comment by TimGeyssens** [comment]
there is also a good idea from @skttl about making the info app extendable (and inbound redirs could make perfect sense as part of that app), since we don't want a wildgrow of content apps.... but that's something for Umbraco core to implement first

**Comment by abjerner** [comment]
Hi @TimGeyssens 

I'm doing a follow-up on the open issues of this package. As the packages already features a property editor for inbound redirects, and since we're moving towards Umbraco 9, we won't be adding a content app to the Umbraco 8 package.

But on the plus side, the Umbraco 9 package already has a content app 😉

**Comment by TimGeyssens** [comment]
sounds good! great work @abjerner
