### ISSUE TITLE
Umbraco installation with multiple sites and user access

### ISSUE THREAD

**Issue by webtimisten** [skybrud/Skybrud.Umbraco.Redirects#70]
I have a site containing multiple sites (8 as of now) where users only have access to one or more.

Is it possible to only view the sites the user has access to? For now it look like it's only supported when picking the destination.

And is is possible to add the domain before or after the node name, to be able to differentiate the sites from each other?

![Skærmbillede 2020-09-02 kl  11 15 14](https://user-images.githubusercontent.com/2109519/91964619-a82c7680-ed0f-11ea-9ca1-f69ad1c877a7.png)
![Skærmbillede 2020-09-02 kl  11 17 24](https://user-images.githubusercontent.com/2109519/91964626-aa8ed080-ed0f-11ea-8e38-3235f0c44281.png)
![Skærmbillede 2020-09-02 kl  11 17 52](https://user-images.githubusercontent.com/2109519/91964630-aa8ed080-ed0f-11ea-9181-88b916dfb6c9.png)

**Comment by abjerner** [comment]
Hi @webtimisten,

As we talked about on Slack the other day, adding user permissions to the package is not an easy task. Besides the development to enable this, it will also require a bit of consideration how to best implement this, as different solutions have different requirements. At this time, it's not a feature I or @skybrud currently can set time aside to work on.

Similar to how you can add a redirects property editor to show redirects pointing to the current page, I'd like to add another property editor for showing redirects of a given site. Then instead of using the dashboard, you could add this property editor to the site node instead. I'd imagine this would be an easier task than adding full support for user permissions.

<hr />

For the site picker, it may be a bit more complex than what I initially thought and we talked about on Slack. In your case, you have a node above the front page node holding the domain, which why you'll get the eight *Forside* sites.

At @skybrud we typically have a node serving as what we call a domain container, and then the front page and other content lives below this domain container node. The domain container is either named after the domain it self, or a friendly name to identify the site.

There are likely to be other ways people set up their sites, and a solution should ideally handle as many of these. Also, a root node (site) has a 1:* relation to it's domain, meaning that a root node can have more than one domain assigned to it.

![image](https://user-images.githubusercontent.com/3634580/92323945-08d3f000-f03d-11ea-92cc-3e8fe5147c0c.png)

I've tried to play around with something like on the screenshot above, which could be a possible solution. But domains doesn't have a particular order in Umbraco, so showing the first domain in the list we get from Umbraco, may not be the correct domain in the given context.

For the reasons above, I'm leaning towards keeping the name as it is currently, but provide an event in C# that lets developers customize the name of each site at runtime. Could this be a viable solution in your case? It oculd be something like this:

```csharp
RedirectsService.SendingRootNodesModel += delegate(object sender, RedirectRootNode[] nodes)
{

    foreach (var node in nodes)
    {

        if (node.Domains.Length == 1)
        {
            node.Name += " (" + node.Domains[0].Name + ")";
        }
        else if (node.Domains.Length > 1)
        {
            node.Name += " (" + node.Domains[0].Name + " +" + (node.Domains.Length - 1) + " more)";
        }

    }

};
```

I think this will provide the most amount of flexibility, but would require developers to write a bit of their own code.

**Comment by abjerner** [comment]
Hi @webtimisten 

As we're moving towards Umbraco 9, I'm going through and closing older issues for Umbraco 8, which is also why I'm closing this issue.

An event like what I described in my last comment still does make sense for Umbraco 9, but it's not something with a high priority.   So for now I've marked the issue as **could-have** (so we can find it later), and closed it.
