### ISSUE TITLE
Updated existing redirect

### ISSUE THREAD

**Issue by ismailmayat** [skybrud/Skybrud.Umbraco.Redirects#9]
Anders,

I created a new redirect and the destination was an umbraco page.  I then went to edit it and set it to an external page however I cannot do that the url part is now fixed. Only thing I can do is delete and recreate.

Am I missing something?

Regards

Ismail

**Comment by abjerner** [comment]
Hi Ismail,

The dialog we're using is really just Umbraco's default linkpicker dialog, which - at least for some parts - isn't that user friendly due to some "point of no return" states.

Ideally we should create or own dialog or improve Umbraco's through a pull request, but it's not something  I have looked into yet.

**Comment by ismailmayat** [comment]
Anders,

Yeah I could have sworn that the umbraco one has x in red to remove currently picked item?  Very wierd

**Comment by abjerner** [comment]
@ismailmayat We're using the linkpicker dialog, which is the "old way" to work with the linkpicker. Umbraco also has a newer linkpicker overlay, that looks a little different - but suffers from the same issue.

Anyways, since I agree with you, I have created an issue for the linkpicker overlay here: http://issues.umbraco.org/issue/U4-9542

**Comment by abjerner** [comment]
I'm closing this issue as I have created another [here](https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/29) instead as it is specifically for updating/changing the link picker dialog.
